---

- name: Example task to deploy a template
  ansible.builtin.template:
    src: 'potos.example.j2'
    dest: '/potos.example'
    owner: root
    group: root
    mode: '0755'

- name: Create user profile
  ansible.builtin.copy:
    src: 'etc/dconf/profile/user'
    dest: '/etc/dconf/profile/user'
    mode: '644'
