---

- name: ensure dconf is installed
  ansible.builtin.package:
    name: 'dconf-cli'
    state: present

- name: ensure dconf db directory exists
  ansible.builtin.file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: '0755'

- name: install window manager settings dconf file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/20_advanced_wm_settings.j2'
    dest: '/etc/dconf/db/local.d/20_advanced_wm_settings'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: install gnome terminal profiles dconf file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/30_gnome_terminal_profiles.j2'
    dest: '/etc/dconf/db/local.d/30_gnome_terminal_profiles'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: install generic dconf file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/90-potos-custom.j2'
    dest: '/etc/dconf/db/local.d/90-potos-custom'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: ensure dconf profile directory exists
  ansible.builtin.file:
    path: /etc/dconf/profile
    state: directory
    mode: '0755'

- name: Enable user profile
  ansible.builtin.copy:
    src: 'etc/dconf/profile/user'
    dest: '/etc/dconf/profile/user'
    mode: '644'
  notify: 'Rebuild dconf database'

- name: Install wm toggle script
  ansible.builtin.copy:
    src: 'usr/local/bin/toggle-wm'
    dest: '/usr/local/bin/toggle-wm'
    mode: '755'
