---

- name: user profile directory
  ansible.builtin.file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: '0755'

- name: dconf user profile key file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/00-potos-settings'
    dest: '/etc/dconf/db/local.d/00-potos-settings'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: Enable user profile
  ansible.builtin.copy:
    src: 'etc/dconf/profile/user'
    dest: '/etc/dconf/profile/user'
    mode: '644'
  notify: 'Rebuild dconf database'
