---

- name: Example task to deploy a template
  ansible.builtin.template:
    src: 'potos.example.j2'
    dest: '/potos.example'
    owner: root
    group: root
    mode: '0755'

- name: user profile directory
  ansible.builtin.file:
    path: /etc/dconf/db/user.d
    state: directory
    mode: '0755'

- name: dconf user profile key file
  ansible.builtin.template:
    src: 'etc/dconf/db/user.d/00-potos-settings'
    dest: '/etc/dconf/db/user.d/00-potos-settings'
  notify: 'Rebuild dconf database'

- name: Enable user profile
  ansible.builtin.copy:
    src: 'etc/dconf/profile/user'
    dest: '/etc/dconf/profile/user'
    mode: '644'
  notify: 'Rebuild dconf database'
