---

- name: ensure dconf is installed
  ansible.builtin.package:
    name: 'dconf-cli'
    state: present

- name: ensure dconf db directory exists
  ansible.builtin.file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: '0755'

- name: dconf generic user profile key file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/90-potos-custom.j2'
    dest: '/etc/dconf/db/local.d/90-potos-custom'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: dconf window manager user profile key file
  ansible.builtin.template:
    src: 'etc/dconf/db/local.d/20_advanced_wm_settings.j2'
    dest: '/etc/dconf/db/local.d/20_advanced_wm_settings'
    mode: '0644'
  notify: 'Rebuild dconf database'

- name: ensure dconf profile directory exists
  ansible.builtin.file:
    path: /etc/dconf/profile
    state: directory
    mode: '0755'

- name: Enable user profile
  ansible.builtin.copy:
    src: 'etc/dconf/profile/user'
    dest: '/etc/dconf/profile/user'
    mode: '644'
  notify: 'Rebuild dconf database'
