---

- name: Verify
  hosts: all
  gather_facts: no

  # todo: path: "/etc/dconf/profile/user"
  tasks:
    - name: check if template has been applied
      ansible.builtin.stat:
        path: "/etc/dconf/db/local.d/00-potos-settings"
      register: out
      changed_when: false
      failed_when:
        - not out.stat.exists
